export type FontSize =
  | "text-xs"
  | "text-sm"
  | "sm:text-sm"
  | "text-base"
  | "text-lg"
  | "text-xl"
  | "text-2xl"
  | "text-3xl"
  | "text-4xl"
  | "text-5xl"
  | "text-6xl"
  | "text-7xl"
  | "text-8xl"
  | "text-9xl"
  | "text-[6px]"
  | "text-[7px]"
  | "text-[8px]"
  | "text-[9px]"

