export type FontSize =
  | "text-xs"
  | "text-sm"
  | "sm:text-sm"
  | "text-base"
  | "text-lg"
  | "text-xl"
  | "text-2xl"
  | "text-3xl"
  | "text-4xl"
  | "text-5xl"
  | "text-6xl"
  | "text-7xl"
  | "text-8xl"
  | "text-9xl"
  | "text-[0.75rem]"
  | "text-[0.875rem]"
  | "text-[1rem]"
  | "text-[1.125rem]"
  | "text-[1.25rem]"

