export type JustifyContent =
  | 'justify-normal'
  | 'justify-start'
  | 'justify-end'
  | 'justify-center'
  | 'justify-between'
  | 'justify-around'
  | 'justify-evenly'
  | 'justify-stretch'
  | 'sm:justify-normal'
  | 'sm:justify-start'
  | 'sm:justify-end'
  | 'sm:justify-center'
  | 'sm:justify-between'
  | 'sm:justify-around'
  | 'sm:justify-evenly'
  | 'sm:justify-stretch'
