export type PlaceContent =
| 'place-content-center'
| 'place-content-start'
| 'place-content-end'
| 'place-content-between'
| 'place-content-around'
| 'place-content-evenly'
| 'place-content-stretch'
| 'sm:place-content-center'
| 'sm:place-content-start'
| 'sm:place-content-end'
| 'sm:place-content-between'
| 'sm:place-content-around'
| 'sm:place-content-evenly'
| 'sm:place-content-stretch'
