name: "tailwind-ng-core"

trigger:
  paths:
    include:
      - projects/tailwind-ng-core/src/*
      - ci/tailwind-ng-core.yml

pool: Lab

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - group: tailwind-ng-master
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
      - group: tailwind-ng-next
  - ${{ else }}:
      - group: tailwind-ng-dev
  - name: Patch
    value: $[counter(variables.MajorMinor, 0)]

stages:
  - stage: CI
    jobs:
    - job: Build_Test_Publish
      steps:
        - checkout: self
          clean: false
          persistCredentials: true

        - bash: |
            rm -rf $(Build.SourcesDirectory)/artifacts/tailwind-ng-core
            docker build -t tailwind-ng:ci -o "type=local,dest=./" -f ci/tailwind-ng-core.Dockerfile .
          workingDirectory: $(Build.SourcesDirectory)
          displayName: "Run CI"

        - publish: artifacts/tailwind-ng-core
          artifact: drop
          displayName: "Publish artifact"

        - task: PublishCodeCoverageResults@1
          displayName: "Publish code coverage"
          inputs:
            codeCoverageTool: "Cobertura"
            summaryFileLocation: "coverage/tailwind-ng-core/cobertura.xml"
            pathToSources: "$(Build.SourcesDirectory)/coverage/tailwind-ng-core"

        - task: PublishTestResults@2
          displayName: "Publish test results"
          inputs:
            testResultsFormat: "JUnit"
            testResultsFiles: "**/TESTS-*.xml"
            searchFolder: "$(Build.SourcesDirectory)/junit"
            mergeTestResults: true
            testRunTitle: "$(Build.DefinitionName)-v$(ReleaseVersion)-tests-result"

        - bash: |
            npm config set //registry.npmjs.org/:_authToken=$(authToken)
            cd $(Build.SourcesDirectory)/artifacts/tailwind-ng-core
            npm version $(ReleaseVersion)
            npm publish --tag $(ReleaseTag)
          displayName: "Release v$(ReleaseVersion)@$(ReleaseTag)"

