export const KEYBOARD_KEY = {
  // Modifier Keys
  alt: 'Alt',
  altGraph: 'AltGraph',
  capsLock: 'CapsLock',
  control: 'Control',
  fn: 'Fn',
  fnLock: 'FnLock',
  hyper: 'Hyper',
  meta: 'Meta',
  numLock: 'NumLock',
  scrollLock: 'ScrollLock',
  shift: 'Shift',
  super: 'Super',
  symbol: 'Symbol',
  symbolLock: 'SymbolLock',
  // Whitespace Keys
  enter: 'Enter',
  tab: 'Tab',
  space: ' ',
  // Navigation Keys
  arrowDown: 'ArrowDown',
  arrowLeft: 'ArrowLeft',
  arrowRight: 'ArrowRight',
  arrowUp: 'ArrowUp',
  end: 'End',
  home: 'Home',
  pageDown: 'PageDown',
  pageUp: 'PageUp',
  // Editing Keys
  backspace: 'Backspace',
  clear: 'Clear',
  copy: 'Copy',
  crSel: 'CrSel',
  cut: 'Cut',
  delete: 'Delete',
  eraseEof: 'EraseEof',
  exSel: 'ExSel',
  insert: 'Insert',
  paste: 'Paste',
  redo: 'Redo',
  undo: 'Undo',
  // UI Keys
  accept: 'Accept',
  again: 'Again',
  attn: 'Attn',
  cancel: 'Cancel',
  contextMenu: 'ContextMenu',
  execute: 'Execute',
  find: 'Find',
  help: 'Help',
  pause: 'Pause',
  play: 'Play',
  props: 'Props',
  select: 'Select',
  stop: 'Stop',
  // Device Keys
  brightnessDown: 'BrightnessDown',
  brightnessUp: 'BrightnessUp',
  camera: 'Camera',
  eject: 'Eject',
  logOff: 'LogOff',
  power: 'Power',
  powerOff: 'PowerOff',
  printScreen: 'PrintScreen',
  hibernate: 'Hibernate',
  sleep: 'Sleep',
  wakeUp: 'WakeUp',
  // Function keys
  f1: 'F1',
  f2: 'F2',
  f3: 'F3',
  f4: 'F4',
  f5: 'F5',
  f6: 'F6',
  f7: 'F7',
  f8: 'F8',
  f9: 'F9',
  f10: 'F10',
  f11: 'F11',
  f12: 'F12',
  // Phone Keys
  appSwitch: 'AppSwitch',
  call: 'Call',
  cameraFocus: 'CameraFocus',
  endCall: 'EndCall',
  goBack: 'GoBack',
  goHome: 'GoHome',
  headsetHook: 'HeadsetHook',
  lastNumberRedial: 'LastNumberRedial',
  notification: 'Notification',
  mannerMode: 'MannerMode',
  voiceDial: 'VoiceDial',
  // Multimedia Keys
  channelDown: 'ChannelDown',
  channelUp: 'ChannelUp',
  mediaFastForward: 'MediaFastForward',
  mediaPause: 'MediaPause',
  mediaPlay: 'MediaPlay',
  mediaPlayPause: 'MediaPlayPause',
  mediaRecord: 'MediaRecord',
  mediaRewind: 'MediaRewind',
  mediaStop: 'MediaStop',
  mediaTrackNext: 'MediaTrackNext',
  mediaTrackPrevious: 'MediaTrackPrevious',
  // Audio Keys
  audioBalanceLeft: 'AudioBalanceLeft',
  audioBalanceRight: 'AudioBalanceRight',
  audioBassDown: 'AudioBassDown',
  audioBassBoostDown: 'AudioBassBoostDown',
  audioBassBoostToggle: 'AudioBassBoostToggle',
  audioBassBoostUp: 'AudioBassBoostUp',
  audioBassUp: 'AudioBassUp',
  audioFaderFront: 'AudioFaderFront',
  audioFaderRear: 'AudioFaderRear',
  audioSurroundModeNext: 'AudioSurroundModeNext',
  audioTrebleDown: 'AudioTrebleDown',
  audioTrebleUp: 'AudioTrebleUp',
  audioVolumeDown: 'AudioVolumeDown',
  audioVolumeMute: 'AudioVolumeMute',
  audioVolumeUp: 'AudioVolumeUp',
  microphoneToggle: 'MicrophoneToggle',
  microphoneVolumeDown: 'MicrophoneVolumeDown',
  microphoneVolumeMute: 'MicrophoneVolumeMute',
  // Document Keys
  close: 'Close',
  new: 'New',
  open: 'Open',
  print: 'Print',
  save: 'Save',
  spellCheck: 'SpellCheck',
  mailForward: 'MailForward',
  mailReply: 'MailReply',
  mailSend: 'MailSend',
  // Browser Keys
  browserBack: 'BrowserBack',
  browserFavorites: 'BrowserFavorites',
  browserForward: 'BrowserForward',
  browserHome: 'BrowserHome',
  browserRefresh: 'BrowserRefresh',
  browserSearch: 'BrowserSearch',
  browserStop: 'BrowserStop',
  // Numeric Keypad Keys
  decimal: 'Decimal',
  key11: 'Key11',
  key12: 'Key12',
  multiply: 'Multiply',
  add: 'Add',
  divide: 'Divide',
  subtract: 'Subtract',
  separator: 'Separator',
  0: '0',
  1: '1',
  2: '2',
  3: '3',
  4: '4',
  5: '5',
  6: '6',
  7: '7',
  8: '8',
  9: '9'
} as const;
